### ISSUE TITLE
Transmission lost all its torrents

### ISSUE THREAD

**Issue by benoitjpnet** [lardbit/nefarious#330]
The Transmission interface is now empty.

I am checking the docker compose base file:

```
  # transmission base service (to be extended)
  transmission-base:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "9091:9091"
      - "51413:51413"  # peer port
    restart: always
    environment:
      - PUID=${HOST_DOWNLOAD_UID:-1000}
      - PGID=${HOST_DOWNLOAD_GID:-1000}
    volumes:
      - ${HOST_DOWNLOAD_PATH:-/tmp}:/downloads
      - ./transmission-settings.json:/config/settings.json:ro
```

**Don't we need a named volume to save Transmission DB / Torrent files (/config folder)?**

I can see the container was saving torrent files in a generated volume `/var/lib/docker/volumes/c5f2b14072fcb646a0d74d9c1e4a60a9c15c08ffb24b426cf02ee84ea2fa7b32/_data/torrents`

But since I did a `docker compose down; docker compose up -d`. I got a new volume for `/config`.

```
            {
                "Type": "volume",
                "Name": "55e1d2afcb60dd75cce3a227962f4c650250c1f372963e110791acf32f59b112",
                "Source": "/var/lib/docker/volumes/55e1d2afcb60dd75cce3a227962f4c650250c1f372963e110791acf32f59b112/_data",
                "Destination": "/config",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }

```

Expected when you `down` and `up` the compose stack. Should people not do it? They should be free to... I believe a named volume must be used for Transmission's `/config` folder to avoid such issues.
