### ISSUE TITLE
[Suggestion] - Update docker-compose.yaml to use VPN with transmission

### ISSUE THREAD

**Issue by voidrot** [lardbit/nefarious#63]
Since using a vpn is very common with a torrent application, it may be helpful to either add an example of using a vpn in the docker-compose or have a separate compose file to use with vpn.

below is the compose file modified to use the docker container with openvpn and transmission from haugene/transmission-openvpn

It still allows access to jacket and transmission web ui according to docs. The only change is that in the nefarious ui, the jacket host has to be changed to `transmission` so that all jacket searches use VPN

Working compose example:
```
version: '2.4'

services:
  # main application
  nefarious:
    labels:
    - com.centurylinklabs.watchtower.enable=true
    image: lardbit/nefarious
    restart: always
    ports:
    - "8000:80"
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
      NEFARIOUS_USER: ${NEFARIOUS_USER:-admin}
      NEFARIOUS_PASS: ${NEFARIOUS_PASS:-admin}
      HOST_DOWNLOAD_PATH: ${HOST_DOWNLOAD_PATH:-/tmp/}
    volumes:
      # persistent named volume for sqlite database
      - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
    - redis
    - jackett
    - celery

  # background task queue
  celery:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lardbit/nefarious
    restart: always
    entrypoint: /env/bin/celery -A nefarious worker --concurrency ${NUM_CELERY_WORKERS:-0} --beat --loglevel=INFO
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
      HOST_DOWNLOAD_PATH: ${HOST_DOWNLOAD_PATH:-/tmp}
      INTERNAL_DOWNLOAD_PATH: /downloads/completed
    volumes:
      - ${HOST_DOWNLOAD_PATH:-/tmp}:/downloads
      # persistent named volume for sqlite database
      - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
      - redis

  # in-memory database for task queue
  redis:
    image: redis
    restart: always
    mem_limit: 200m
    # TODO - use "expose" vs "ports" to limit external access when not in development
    ports:
    - "6379:6379"

  # torrent indexer service
  jackett:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: linuxserver/jackett
    mem_limit: 200m
    restart: always
    network_mode: service:transmission
    depends_on: 
      - transmission
    logging:
      options:
        max-size: 10m
    volumes:
      - jackett-config:/config

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    labels:
      - com.centurylinklabs.watchtower.enable=true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: unless-stopped
    ports:
      - 9091:9091/tcp
      - 9091:9091/udp
      - 8888:8888 # web-proxy
      - 9117:9117 # jackket
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${HOST_DOWNLOAD_PATH:-/tmp}:/data
      - ./transmission-settings.json:/config/settings.json:ro
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - OPENVPN_PROVIDER=VPN_PROVIDER
      - OPENVPN_USERNAME=***********
      - OPENVPN_PASSWORD=***********
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24,172.17.0.0/16
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - GLOBAL_APPLY_PERMISSIONS=true
      - CREATE_TUN_DEVICE=true
    logging:
      driver: json-file
      options:
        max-size: 10m

  # auto update service
  # https://github.com/v2tec/watchtower
  watchtower:
    image: v2tec/watchtower
    restart: always
    command: --label-enable --cleanup
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nefarious-db:
    driver: local
  jackett-config:
    driver: local
```
