### ISSUE TITLE
The download path in transmission is overwritten all the time

### ISSUE THREAD

**Issue by JorTurFer** [lardbit/nefarious#73]
I am running the last version of nefarious image with a docker-compose like this:
```yaml
  nefarious:
    image: lardbit/nefarious:armv7
    container_name: nefarious
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    ports:
    - "8000:80"
    environment:
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
      NEFARIOUS_USER: admin
      NEFARIOUS_PASS: admin
      HOST_DOWNLOAD_PATH: ${HOST_DOWNLOAD_PATH}
    volumes:
      # persistent named volume for sqlite database
      - ${VOLUMES}/nefarious/nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
    - redis
    - jackett
    - celery

  # background task queue
  celery:
    image: lardbit/nefarious:armv7
    container_name: celery
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    entrypoint: /env/bin/celery -A nefarious worker --concurrency ${NUM_CELERY_WORKERS:-0} --beat --loglevel=INFO
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
      HOST_DOWNLOAD_PATH: ${HOST_DOWNLOAD_PATH}
      INTERNAL_DOWNLOAD_PATH: /downloads
    volumes:
      - ${HOST_DOWNLOAD_PATH}:/downloads
      # persistent named volume for sqlite database
      - ${VOLUMES}/nefarious/nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
      - redis

  # in-memory database for task queue
  redis:
    image: arm32v7/redis
    container_name: redis
    restart: unless-stopped
    ports:
    - "6379:6379"
```

After some task executions, my downloads folder looks like this:
![image](https://user-images.githubusercontent.com/36899226/99726982-9a3cf500-2ab7-11eb-9f9a-a05d271e88c8.png)

In this image you can see that the folder .`.nefarious-unprocessed-downloads` is being replicated inside other folders and the new torrents are added in the last nested `.nefarious-unprocessed-downloads`. The problem here is that with this situation, the final path of the series and the movies change all the time and I can't detect the downloaded files in plex.

Maybe my docker-compose is wrong? I tried some different configurations but all the time the folder is changing. I tried fixing the path in the transmission json. It looks like this:

```json
{
    "alt-speed-down": 2000,
    "alt-speed-enabled": true,
    "alt-speed-time-begin": 450,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": true,
    "alt-speed-time-end": 30,
    "alt-speed-up": 10000,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 16,
    "dht-enabled": true,
    "download-dir": "/downloads/complete",
    "download-queue-enabled": true,
    "download-queue-size": 15,
    "encryption": 0,
    "idle-seeding-limit": 300,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": true,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 100,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "{15a5eee232c570df1e95a901c5e320b479a9fd645YTFlxFH",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "username",
    "rpc-whitelist": "*.*.*.*",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": true,
    "seed-queue-size": 25,
    "seedRatioLimit": 50,
    "seedRatioLimited": false,
    "speed-limit-down": 300000,
    "speed-limit-down-enabled": true,
    "speed-limit-up": 300000,
    "speed-limit-up-enabled": true,
    "start-added-torrents": true,
    "trash-original-torrent-files": true,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/watch",
    "watch-dir-enabled": true
}
```

Could you help me with this issue? This software is the best that I tried to automatize the torrent discover and download but I can't use now and I feeld that is because I am configuring wrong it :(
